/*
 * File: app/view/MainViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HomeAccounting.view.MainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.main',

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        Ext.util.Cookies.set('calendarId', newValue);
        var oEvents = Ext.data.StoreManager.get('Events');
        oEvents.getProxy().url = 'https://www.googleapis.com/calendar/v3/calendars/' + newValue + '/events';
        oEvents.load();
    }

});
