/*
 * File: app/model/Event.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HomeAccounting.model.Event', {
	extend: 'Ext.data.Model',

	requires: [
		'Ext.data.field.String',
		'Ext.data.field.Date',
		'Ext.data.field.Number'
	],

	fields: [
		{
			type: 'string',
			name: 'id'
		},
		{
			type: 'string',
			name: 'summary'
		},
		{
			type: 'date',
			convert: function(v, rec) {
				return Ext.Date.parse(v.dateTime, 'c');
			},
			name: 'start',
			dateFormat: 'c'
		},
		{
			type: 'string',
			convert: function(v, rec) {
				var oMerchants = Ext.data.StoreManager.get('Merchants'),
					oItems = Ext.data.StoreManager.get('Items'),
					oTags = Ext.data.StoreManager.get('Tags'),
					i = 0,
					oGeneric,
					fTotal;

				try {
					Ext.apply(rec.data, Ext.JSON.decode(v, true));

					oGeneric = oMerchants.findRecord('name', rec.data.merchant.trim(), 0, false, false, true);
					if(oGeneric === null) {
						oMerchants.add({
							name: rec.data.merchant.trim(),
							total: rec.data.total,
							count: 1,
							min: rec.data.total,
							max: rec.data.total
						});
					}
					else {
						oGeneric.set('total', oGeneric.get('total') + rec.data.total);
						oGeneric.set('count', oGeneric.get('count') + 1);
						if(oGeneric.get('min') > rec.data.total) {
							oGeneric.set('min', rec.data.total);
						}
						if(oGeneric.get('max') < rec.data.total) {
							oGeneric.set('max', rec.data.total);
						}
					}

					for(; i < rec.data.rows.length; i++) {
						fTotal = (rec.data.rows[i].number * rec.data.rows[i].price);

						oGeneric = oItems.findRecord('name', rec.data.rows[i].item.trim(), 0, false, false, true);
						if(oGeneric === null) {
							oItems.add({
								name: rec.data.rows[i].item.trim(),
								total: fTotal,
								count: rec.data.rows[i].number,
								min: rec.data.rows[i].price,
								max: rec.data.rows[i].price
							});
						}
						else {
							oGeneric.set('total', oGeneric.get('total') + fTotal);
							oGeneric.set('count', oGeneric.get('count') + rec.data.rows[i].number);
							if(oGeneric.get('min') > rec.data.rows[i].price) {
								oGeneric.set('min', rec.data.rows[i].price);
							}
							if(oGeneric.get('max') < rec.data.rows[i].price) {
								oGeneric.set('max', rec.data.rows[i].price);
							}
						}

						if(!Ext.isEmpty(rec.data.rows[i].tag)) {
							oGeneric = oTags.findRecord('name', rec.data.rows[i].tag.trim(), 0, false, false, true);
							if(oGeneric === null) {
								oTags.add({
									name: rec.data.rows[i].tag.trim(),
									total: (rec.data.rows[i].number * rec.data.rows[i].price),
									count: rec.data.rows[i].number,
									min: fTotal,
									max: fTotal
								});
							}
							else {
								oGeneric.set('total', oGeneric.get('total') + fTotal);
								oGeneric.set('count', oGeneric.get('count') + 1);
								if(oGeneric.get('min') > fTotal) {
									oGeneric.set('min', fTotal);
								}
								if(oGeneric.get('max') < fTotal) {
									oGeneric.set('max', fTotal);
								}
							}
						}
					}
				}
				catch(e) {
					if(console && console.log) {
						console.log(e);
					}
				}
				return v;
			},
			name: 'description'
		},
		{
			type: 'string',
			name: 'merchant'
		},
		{
			type: 'date',
			name: 'date',
			dateFormat: 'Y-m-d'
		},
		{
			type: 'date',
			name: 'time',
			dateFormat: 'H:i:s'
		},
		{
			type: 'float',
			name: 'total'
		},
		{
			name: 'rows'
		}
	]
});