/*
 * File: app/model/Generic.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HomeAccounting.model.Generic', {
	extend: 'Ext.data.Model',

	requires: [
		'Ext.data.field.String',
		'Ext.data.field.Number'
	],

	fields: [
		{
			type: 'string',
			name: 'name'
		},
		{
			type: 'float',
			name: 'total'
		},
		{
			type: 'float',
			name: 'count'
		},
		{
			type: 'float',
			name: 'min'
		},
		{
			type: 'float',
			name: 'max'
		}
	],

	getHint: function() {
		return 'Total: ' + Ext.util.Format.currency(this.get('total')) +
			'<br />Count: ' + Ext.util.Format.number(this.get('count'), '0.###') +
			'<br />Min: ' + Ext.util.Format.currency(this.get('min')) +
			'<br />Max: ' + Ext.util.Format.currency(this.get('max'));
	}

});