/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
	models: [
		'Calendar',
		'Event',
		'Generic'
	],
	stores: [
		'Calendars',
		'Events',
		'Merchants',
		'Items',
		'Tags'
	],
	views: [
		'Main',
		'EditWindow',
		'RowContainer',
		'GridMenu'
	],
	name: 'HomeAccounting',

	launch: function() {
		Ext.create('HomeAccounting.view.Main');
		var date = new Date(),
			y = date.getFullYear(),
			m = date.getMonth();

		Ext.USE_NATIVE_JSON = true;
		Ext.util.Format.currencySign = '€';
		Ext.util.Format.decimalSeparator = ',';
		Ext.util.Format.thousandSeparator = '.';

		sActualTimeZone = null;

		Ext.ComponentQuery.query('#startDate')[0].setValue(new Date(y, m, 1));
		Ext.ComponentQuery.query('#endDate')[0].setValue(new Date(y, m + 1, 0, 23, 59, 59));

		gapi.load('auth', function() {
			gapi.auth.authorize({
				'client_id': '137779780771-bl0ae35ftcuvloajal02idrsgnost9i7.apps.googleusercontent.com',
				'scope': 'https://www.googleapis.com/auth/calendar'
			}, function() {
				var params = gapi.auth.getToken();

				Ext.data.StoreManager.get('Calendars').getProxy().extraParams.access_token = params.access_token;
				Ext.data.StoreManager.get('Events').getProxy().extraParams.access_token = params.access_token;
				Ext.ComponentQuery.query('#calendarId')[0].setValue(Ext.util.Cookies.get('calendarId'));
			});
		});
	}

});
